language: rust
dist: trusty
sudo: false
branches:
  except:
  - staging.tmp
  - trying.tmp
cache: cargo
os:
- linux
- osx
- windows
rust:
- nightly
install: |
    # Required for Racer autoconfiguration
    rustup component add rust-src
    rustup component add rust-analysis
script:
- cargo build -v
- cargo test -v
env:
  global:
  - RUSTFLAGS=--cfg=enable_tooltip_tests
  - RUST_BACKTRACE=1
  - RLS_TEST_WAIT_FOR_AGES=1
