language: rust
dist: trusty
sudo: false
branches:
  except:
  - staging.tmp
  - trying.tmp
cache:
  cargo: true
  timeout: 300
# Quicker to fetch that during the build than to transmit as part of the cache
before_cache:
- rm -rf /home/travis/.cargo/registry
os:
- linux
- osx
- windows
rust:
- nightly
install: |
    # Required for Racer autoconfiguration
    rustup component add rust-src
    rustup component add rust-analysis
script:
- git config --global core.autocrlf input
- cargo build -v
- cargo test -v
env:
  global:
  - RUSTFLAGS=--cfg=enable_tooltip_tests
  - RUST_BACKTRACE=1
  - RLS_TEST_WAIT_FOR_AGES=1
