branches:
  except:
  - staging.tmp
  - trying.tmp

environment:
  global:
    PROJECT_NAME: rls
    RUSTFLAGS: --cfg=enable_tooltip_tests
    RUST_BACKTRACE: 1
  matrix:
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly
      BITS: 32
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly
      BITS: 64

install:
  - set PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  # Install rust
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%-%TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  # Required for Racer autoconfiguration
  - rustup component add rust-src
  - rustup component add rust-analysis
  # Print version info
  - rustc -Vv
  - cargo -V


build: false

test_script:
  # compile #[cfg(not(test))] code
  - cargo build --verbose
  - cargo test --verbose

cache:
  - target -> Cargo.lock
  - C:\Users\appveyor\.cargo\registry -> Cargo.lock
