[package]
name = "rls-rustc"
version = "0.6.0"
edition = "2018"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
description = "A simple shim around rustc to allow using save-analysis with a stable toolchain"
license = "Apache-2.0/MIT"
repository = "https://github.com/rust-lang/rls"
categories = ["development-tools"]

[patch.crates-io]
jsonrpc-ipc-server = { git = "https://github.com/Xanewok/jsonrpc", branch = "event-loop-reactor", optional = true }
jsonrpc-core = { git = "https://github.com/Xanewok/jsonrpc", branch = "event-loop-reactor", optional = true }
jsonrpc-derive = { git = "https://github.com/Xanewok/jsonrpc", branch = "event-loop-reactor", optional = true }
# We don't use it directly but we need to also patch this peer dependency
# because we only partially patch the dep tree (and trait implementations
# conflict due to monomorphization)
jsonrpc-pubsub = { git = "https://github.com/Xanewok/jsonrpc", branch = "event-loop-reactor", optional = true }

[dependencies]
env_logger = "0.6"
log = "0.4"
failure = "0.1"
rand = "0.6"
parity-tokio-ipc = { version = "0.1", optional = true }
tokio = { version = "0.1", optional = true }
futures = { version = "0.1", optional = true }
jsonrpc-ipc-server = { version = "12", optional = true }
jsonrpc-core = { version = "12", optional = true }
jsonrpc-core-client = { version = "12", optional = true }
jsonrpc-derive = {version = "12", optional = true }
serde = {version = "1", optional = true}
jsonrpc-server-utils = {version = "12", optional = true }

[features]
ipc = ["parity-tokio-ipc", "tokio", "futures", "jsonrpc-ipc-server", "jsonrpc-core-client", "jsonrpc-derive", "jsonrpc-core", "serde", "jsonrpc-server-utils"]
default = ["ipc"] # TODO: Remove me
