[package]
name = "rls-rustc"
version = "0.6.0"
edition = "2018"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
description = "A simple shim around rustc to allow using save-analysis with a stable toolchain"
license = "Apache-2.0/MIT"
repository = "https://github.com/rust-lang/rls"
categories = ["development-tools"]

[dependencies]
parity-tokio-ipc = { version = "0.1", optional = true }
tokio = { version = "0.1", optional = true }
futures = { version = "0.1", optional = true }

[features]
ipc = ["parity-tokio-ipc", "tokio", "futures"]
default = ["ipc"] # TODO: Remove me
