[package]
name = "rls-rustc"
version = "0.5.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
description = "A simple shim around rustc to allow using save-analysis with a stable toolchain"
license = "Apache-2.0/MIT"
repository = "https://github.com/nrc/rls-rustc"
categories = ["development-tools"]

[dependencies]
